import type { Post, Comment, SuggestedUser, User } from "@/types";

export const currentUser: User = {
  id: "you",
  username: "dilshan",
  displayName: "Dilshan",
  avatarInitial: "D",
  avatarGradient: "from-[#e8ff47] to-emerald-400",
  isVerified: true,
  followers: 2841,
  following: 391,
  posts: 47,
  bio: "📸 Photographer & visual storyteller | 🌏 Capturing moments that matter",
};

export const mockPosts: Post[] = [
  {
    id: "1",
    user: {
      id: "u1",
      username: "maya_k",
      displayName: "Maya Krishnan",
      avatarInitial: "M",
      avatarGradient: "from-violet-500 to-purple-700",
      isVerified: true,
    },
    mediaEmoji: "🌄",
    mediaLabel: "Shot on Fujifilm X-T5",
    mediaType: "image",
    aspectRatio: "square",
    caption: "Golden hour never hits the same twice. Worth every step of the climb.",
    tags: ["#landscape", "#goldenhour", "#fujifilm"],
    likes: 2418,
    comments: 148,
    isLiked: true,
    isSaved: false,
    location: "Ridge Trail, Ooty",
    createdAt: "2h",
  },
  {
    id: "2",
    user: {
      id: "u2",
      username: "devraj",
      displayName: "Dev Raj",
      avatarInitial: "D",
      avatarGradient: "from-pink-500 to-rose-600",
      isVerified: false,
    },
    mediaEmoji: "🎸",
    mediaLabel: "Live at Echo Lounge · 4K",
    mediaType: "video",
    aspectRatio: "landscape",
    caption: "Opening night at Echo Lounge — the energy in that room was electric.",
    tags: ["#music", "#livemusic", "#indie"],
    likes: 892,
    comments: 64,
    isLiked: false,
    isSaved: true,
    location: "Echo Lounge, Bangalore",
    createdAt: "5h",
  },
  {
    id: "3",
    user: {
      id: "u3",
      username: "laila.v",
      displayName: "Laila Verma",
      avatarInitial: "L",
      avatarGradient: "from-sky-400 to-cyan-500",
      isVerified: true,
    },
    mediaEmoji: "🌿",
    mediaLabel: "Morning light study",
    mediaType: "image",
    aspectRatio: "square",
    caption: "Finding stillness in Sunday light. A quiet corner and a cup of tea.",
    tags: ["#calm", "#slowliving", "#interior"],
    likes: 1102,
    comments: 93,
    isLiked: false,
    isSaved: false,
    location: "Home studio",
    createdAt: "1d",
  },
];

export const mockComments: Comment[] = [
  {
    id: "c1",
    user: {
      id: "u2",
      username: "devraj",
      displayName: "Dev Raj",
      avatarInitial: "D",
      avatarGradient: "from-pink-500 to-rose-600",
    },
    text: "This colour palette is unreal! 🔥 The way the light hits the ridge...",
    createdAt: "1h",
    likes: 24,
    isLiked: false,
    replies: [
      {
        id: "c1r1",
        user: {
          id: "u1",
          username: "maya_k",
          displayName: "Maya Krishnan",
          avatarInitial: "M",
          avatarGradient: "from-violet-500 to-purple-700",
        },
        text: "Thank you so much! Nature just does its thing 🙏",
        createdAt: "58m",
        likes: 8,
        isLiked: false,
      },
      {
        id: "c1r2",
        user: {
          id: "u4",
          username: "artxneo",
          displayName: "Art x Neo",
          avatarInitial: "A",
          avatarGradient: "from-emerald-400 to-teal-500",
        },
        text: "Film simulation? This looks like Velvia 🎞️",
        createdAt: "45m",
        likes: 5,
        isLiked: false,
      },
      {
        id: "c1r3",
        user: {
          id: "u1",
          username: "maya_k",
          displayName: "Maya Krishnan",
          avatarInitial: "M",
          avatarGradient: "from-violet-500 to-purple-700",
        },
        text: "@artxneo Exactly! Classic Velvia 100 🎨",
        createdAt: "40m",
        likes: 11,
        isLiked: false,
      },
    ],
  },
  {
    id: "c2",
    user: {
      id: "u3",
      username: "laila.v",
      displayName: "Laila Verma",
      avatarInitial: "L",
      avatarGradient: "from-sky-400 to-cyan-500",
    },
    text: "Which trail is this?? I need coordinates immediately 😭",
    createdAt: "45m",
    likes: 17,
    isLiked: true,
    replies: [],
  },
  {
    id: "c3",
    user: {
      id: "u5",
      username: "sora",
      displayName: "Sora",
      avatarInitial: "S",
      avatarGradient: "from-violet-400 to-indigo-500",
    },
    text: "You make me want to quit my desk job and become a nature photographer 🌊",
    createdAt: "30m",
    likes: 41,
    isLiked: false,
    replies: [],
  },
];

export const suggestedUsers: SuggestedUser[] = [
  {
    id: "su1",
    username: "sora",
    displayName: "Sora",
    avatarInitial: "S",
    avatarGradient: "from-violet-400 to-indigo-500",
    reason: "Followed by devraj",
    mutualFriends: 2,
  },
  {
    id: "su2",
    username: "artxneo",
    displayName: "Art x Neo",
    avatarInitial: "A",
    avatarGradient: "from-emerald-400 to-teal-500",
    reason: "New to Lumora",
  },
  {
    id: "su3",
    username: "priya_s",
    displayName: "Priya S.",
    avatarInitial: "P",
    avatarGradient: "from-orange-400 to-rose-500",
    reason: "3 mutual friends",
    mutualFriends: 3,
  },
  {
    id: "su4",
    username: "kai.film",
    displayName: "Kai Film",
    avatarInitial: "K",
    avatarGradient: "from-amber-400 to-orange-500",
    reason: "Popular in your area",
  },
  {
    id: "su5",
    username: "neo_wave",
    displayName: "Neo Wave",
    avatarInitial: "N",
    avatarGradient: "from-sky-400 to-blue-500",
    reason: "New to Lumora",
  },
];

export const mockStories = [
  { id: "s1", username: "maya_k", emoji: "🌅", seen: false },
  { id: "s2", username: "devraj", emoji: "🎸", seen: false },
  { id: "s3", username: "sora", emoji: "🏄", seen: true },
  { id: "s4", username: "laila.v", emoji: "🌿", seen: false },
  { id: "s5", username: "artxneo", emoji: "🎨", seen: true },
  { id: "s6", username: "priya_s", emoji: "🦋", seen: false },
];
